 dist: xenial
 language: cpp
 compiler: clang

 before_script:
         - echo "deb http://dl.bintray.com/alexisvabel/otus-cpp xenial main" | sudo tee -a /etc/apt/sources.list
         - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
         - sudo add-apt-repository ppa:boost-latest/ppa
         - sudo apt update
         - sudo apt install libspdlog-dev -y
         - sudo apt install libboost-all-dev -y
         - sudo apt install async
 script:
         - cmake .
         - cmake --build .
         - cmake --build . --target package
         - doxygen Doxyfile 2>&1 | tee doxygen.log
 deploy:
         - provider: script
           skip_cleanup: true
           script:
             - curl -T bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexisvabel:$BINTRAY_API_KEY "https://api.bintray.com/content/alexisvabel/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"



